---
Name: cricket-blog
---
SilverStripe\Blog\Model\Blog:
  allowed_children:
    - SilverStripe\Blog\Model\Blog
    - Suilven\CricketSite\Model\MatchReport

# Configure Admin Extensions:

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "suilven/cricket-blog: admin/client/dist/styles/bundle.css"
  extra_requirements_javascript:
    - "suilven/cricket-blog: admin/client/dist/js/bundle.js"

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Suilven\CricketSite\SiteConfig\CricketSiteConfig

#SilverStripe\CMS\Model\SiteTree: << gets picked up but fails on the customise method
SilverStripe\Control\Controller:
  extensions:
    - Suilven\CricketSite\Extensions\GroundWeatherExtension

