---
Name: cricket-blog
---
SilverStripe\Blog\Model\Blog:
  allowed_children:
    - SilverStripe\Blog\Model\Blog
    - Suilven\CricketSite\Model\MatchReport

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Suilven\CricketSite\SiteConfig\CricketSiteConfig

#SilverStripe\CMS\Model\SiteTree: << gets picked up but fails on the customise method
SilverStripe\Control\Controller:
  extensions:
    - Suilven\CricketSite\Extensions\GroundWeatherExtension

